const Database = [
    {
        id:0,
        User:"sobhan",
        Email:'examle@gmail.com'
    },{
        id:1,
        User:"ali",
        Email:'examle@gmail.com'
    },
    {
        id:2,
        User:"Mahdi",
        Email:'examle@gmail.com'
    },
    {
        id:3,
        User:"Arshia",
        Email:'examle@gmail.com'
    },{
        id:4,
        User:"khosro",
        Email:'examle@gmail.com'
    }
    ,{
        id:5,
        User:"mohsen",
        Email:'examle@gmail.com'
    }
    ,{
        id:6,
        User:"keykavos",
        Email:'examle@gmail.com'
    }
];
export default Database;
